### ISSUE TITLE
Hero Siege Timeline

### ISSUE THREAD

**Issue by Cpfuzzyz** [AyronK/arpg-timeline#107]
Say's "Next" for Season 5 is August 9th or 16th, it's not Season 5 it's 4.5 and the confirmed date for 4.5 is 16th.

**Comment by AyronK** [comment]
@Cpfuzzyz I cannot find an official announcement other than the season 4 ends on 16th August. Could you help me find the right source?

**Comment by AyronK** [comment]
Also, do you know what time Hero Siege usually starts?

**Comment by Cpfuzzyz** [comment]
> @Cpfuzzyz I cannot find an official announcement other than the season 4 ends on 16th August. Could you help me find the right source?

![Discord_3QT42IIdsg](https://github.com/user-attachments/assets/debd30d3-bea2-4053-9fbb-c6f01af9889e)

**Comment by Cpfuzzyz** [comment]
> Also, do you know what time Hero Siege usually starts?

Usually, the specific time can be different on a Friday but for 4.5 it will start on August 16th, 2024 6:00 AM CST

**Comment by AyronK** [comment]
Thank you. I didn't get that yet because it seems to just be posted on discord and not on official RSS / Patch Notes channels. I'll update the date.
