### ISSUE TITLE
Filters don't work

### ISSUE THREAD

**Issue by KazumaIgarashi** [AyronK/arpg-timeline#119]
**Describe the bug**
If you press "Filter Games" in the upper left corner of the screen, nothing will be displayed on the screen.

**To Reproduce**

1. Go to 'https://arpg-timeline.ayronk.com/'
2. Click on 'Filter Games'
3. See error

**Screenshots**
![ss](https://github.com/user-attachments/assets/8e194a5d-9bc6-4a94-aa12-4c00b9017c7a)

**Desktop (please complete the following information):**

- OS: Windows11
- Browser: chrome
- Version: v129.0.6668.71

**Comment by AyronK** [comment]
Thank you for reporting it, I will fix it soon.

**Comment by AyronK** [comment]
@KazumaIgarashi I cannot reproduce it.
![image](https://github.com/user-attachments/assets/153bc9f3-6405-48b7-bbb3-ce9e691ef4dc)

Are you sure you're not using any third party extensions that could interfere with the website?

**Comment by KazumaIgarashi** [comment]
Thank you for your reply.
I get the same result when I disable extensions in Chrome and use an incognito window.

I did the same test on live.browserstack.com and got the same screen.

![0LcGK2Z](https://github.com/user-attachments/assets/fc7a8560-d4f8-4200-b19b-d2f2543aeea4)

![d22uqSV](https://github.com/user-attachments/assets/7b88b515-04a1-4c41-9e5a-cf85f0f59ad1)

**Comment by AyronK** [comment]
Okay, this is odd then. Maybe it's caused by something that is culture specific. 

I can see that https://react.dev/errors/130 error isn't very helpful in that regard. Is there any other error in the console above it?

**Comment by KazumaIgarashi** [comment]
I just checked and the problem has been fixed, thank you.

**Comment by AyronK** [comment]
Ok, let me know if that happens again :)
