### ISSUE TITLE
Add games

### ISSUE THREAD

**Issue by AyronK** [AyronK/arpg-timeline#39]
# New game considerations:

- [x] Diablo II Resurrected,
- [x] Diablo III,
- [x] Diablo IV,
- [x] Path of Exile
- [x] Path of Exile 2,
- [x] Torchlight: Infinite,
- [x] Last Epoch,
- [x] PD2 (Diablo II Mod), 
- [x] Hero Siege, 
- [x] Undecember,
- [x] MedianXL 
- [x] pathofdiablo
- [ ] ~Grim Dawn~ - [comment explaining](https://github.com/AyronK/arpg-timeline/issues/39#issuecomment-2221175759)
- [ ] ~Titan Quest 2,~ - unlikely to have seasons/ladders
- [ ] ~Spellwake~ - peak playerbase extremely low

Help wanted needed with maintaining the timelines for these games.

**Comment by ulumulu2** [comment]
pd2 will be rly nice if you add it

**Comment by AyronK** [comment]
(Spellwake)[https://store.steampowered.com/app/921070/Spellwake/] #64

**Comment by AyronK** [comment]
Skipping Spellwake, peak concurrent palyers **48**, 6 years ago.
![image](https://github.com/AyronK/arpg-timeline/assets/26150059/2b129f4c-25c8-4ff2-8cf1-46dc23ce5ea0)
