### ISSUE TITLE
Allow visualization using a timeline or similar

### ISSUE THREAD

**Issue by zakaluka** [AyronK/arpg-timeline#47]
**Is your feature request related to a problem? Please describe.**
Currently, you have to look at each game separately and construct a timeline in your head or on paper.  As more games are added, keeping the dates straight becomes more and more annoying.

**Describe the solution you'd like**
It would be nice to visualize the timeline, similar to 
![image](https://github.com/AyronK/arpg-timeline/assets/1186367/a5df35c0-4ada-413a-bdcf-975d62f5669d)

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by AyronK** [comment]
Yes, this is already planned. Thank you for submitting the issue!

**Comment by AyronK** [comment]
https://blog.logrocket.com/comparing-best-react-timeline-libraries/

**Comment by AyronK** [comment]
https://github.com/frappe/gantt

**Comment by AyronK** [comment]
https://www.react-google-charts.com/examples/gantt

**Comment by AyronK** [comment]
https://matematuk.github.io/gantt-task-react/

**Comment by AyronK** [comment]
@zakaluka early access of the feature can be tested here https://66a1808627d684595c62f66e--arpg-timeline.netlify.app/ if you'd like to share feedback

**Comment by AyronK** [comment]
Done :)
