### ISSUE TITLE
Improve mobile view

### ISSUE THREAD

**Issue by AyronK** [AyronK/arpg-timeline#51]
Ideas

![image](https://github.com/AyronK/arpg-timeline/assets/26150059/3c261d6c-cd73-4a03-a8d1-d7f6dd25cf66)
![image](https://github.com/AyronK/arpg-timeline/assets/26150059/74b57d83-9782-4b8f-bf0f-0b8a3d6b35d1)

**Comment by savicaleksa** [comment]
The second one looks cleaner imo because almost everything is aligned. I'm pretty sure I can make it if you're interested, but before that, I just need to know if by making this you plan to remove the starting date of the current season/cycle from the card component (in this case Feb 21)?

**Comment by AyronK** [comment]
I believe start date is not an important information for an ongoing season and it is okay to remove on mobile to reduce the clutter. I will try to prepare the codebase for contributions next week. To be honest I have not expected so much interest and I am all in pieces at the moment :D Although changes for this issue are strictly targeting one component `<Card>` so it should be fairly easy to run a PR if you'd like to. Let me know if there is something missing in terms of permissions and I will address it asap :)

**Comment by savicaleksa** [comment]
Sounds good, I'll start working on it now. One more question, should I make the changes to layout for mobile version only or both mobile and desktop?

**Comment by AyronK** [comment]
Preferably keep the desktop layout unchanged. The mobile layout should be doable with just a bit of DOM/flex manipulations on the existing component with tailwind breakpoints. Let me know if you face a problem.
