### ISSUE TITLE
Alternative view: Timeline

### ISSUE THREAD

**Issue by MrOtter6** [AyronK/arpg-timeline#65]
The possibility to change the view to a timeline to better visualize the distance between the individual updates of the games.

Perhaps the lengths of the seasons could be displayed as bars in the timeline.
![Mockup](https://github.com/AyronK/arpg-timeline/assets/174992853/10dae91d-0c1c-4574-93c7-1946bae38f4e)

**Comment by AyronK** [comment]
Duplicate of #47
